# Combining arrays

In [1]:
import numpy as np
import numpy.random as npr

In [2]:
array_1 = [[1,2],[3,4]]
array_2 = [[5,6],[7,8]]

### concatenate appends arrays of the same dimension along a specified axis (optional)

In [39]:
np.concatenate((array_1, array_2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
np.concatenate((array_1,array_2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [41]:
x = npr.randint(20,size=20).reshape(10,2)
y = np.arange(10)

In [42]:
np.concatenate((x,y))

ValueError: all the input arrays must have same number of dimensions

### append allows you to add values without requiring the same dimensionality

In [44]:
z = np.append(x,y)

the resulting array is "flattened"

### You can reshape the array to regain dimensions

In [46]:
z = z.reshape(10,3)
print(z)
print(z.shape)

[[17 19  7]
 [ 1  6  6]
 [ 9  5 12]
 [19  7  6]
 [16  9 10]
 [ 1  4  7]
 [ 5  7  0]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
(10, 3)


### But what if you wanted to add a third "column"?

In [48]:
merged = np.zeros((10,3))
merged[:, :2] = x
merged[:, 2] = y

In [49]:
print(merged)

[[17. 19.  0.]
 [ 7.  1.  1.]
 [ 6.  6.  2.]
 [ 9.  5.  3.]
 [12. 19.  4.]
 [ 7.  6.  5.]
 [16.  9.  6.]
 [10.  1.  7.]
 [ 4.  7.  8.]
 [ 5.  7.  9.]]
