# Flattening Arrays

In [5]:
import numpy as np

In [14]:
arr = np.arange(27).reshape(3,3,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Sometimes you need to flatten an ndim array to a single dimension

In [9]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Sometimes you want to reassign values --> use .flat

In [15]:
arr_copy = arr.copy()
arr_copy.flat = 3
arr_copy

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

### You can choose indexes to reassign 

In [11]:
arr_copy.flat[[1,4,7,10]] = 1
arr_copy

array([[[3, 1, 3],
        [3, 1, 3],
        [3, 1, 3]],

       [[3, 1, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

### You can reassign a range of indexes

In [12]:
arr_copy.flat[1:9] = 0
arr_copy

array([[[3, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[3, 1, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

### You can also remove dimensions with reshape

In [16]:
arr.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])