# NumPy Refresher

### Load NumPy and check version

In [6]:
import numpy as np
np.__version__

'1.16.2'

### NumPy is a huge library geared toward scientific computing -- most known for it's true array container

In [8]:
x = np.arange(10)
print(x)
type(x)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

### Typically, computationally faster than working with Python Lists 

In [9]:
y = np.arange(1000000)
y = y ** 2

In [10]:
z = list(range(1000000))
z = z ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Data must be all of the same type - NumPy will attempt to coerce data

In [11]:
animal = ['Dog', 'Mammal', 45, 7]
print(animal)

['Dog', 'Mammal', 45, 7]


In [12]:
np.array(animal)

array(['Dog', 'Mammal', '45', '7'], dtype='<U6')

### Arrays can be "n"-dimensional --but most commonly one, two or three dimensional

In [14]:
ndim = np.arange(27).reshape(3,3,3)
print(ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [15]:
twos = np.arange(16).reshape(2,2,2,2)
print(twos)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


### Sometimes it's easier to define a data holder before actually the getting or generating the data

In [16]:
print(np.ones((3,5)), end='\n\n')
print(np.zeros((3,5)), end='\n\n')
print(np.eye(3,5))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Subsetting can be on one or more dimensions

In [17]:
data = np.random.randint(10, size=15)
print(data)

[6 2 9 8 1 3 6 2 5 5 1 6 0 4 4]


In [20]:
data[4:8]

array([1, 3, 6, 2])

In [21]:
data = data.reshape(3,5)
data

array([[6, 2, 9, 8, 1],
       [3, 6, 2, 5, 5],
       [1, 6, 0, 4, 4]])

In [24]:
data[0,0]

6