# Indirect Sorting with argsort

In [1]:
import numpy as np

### Argsort --> returns indices that would sort an array, leaves array unchanged

In [2]:
x = np.array([3,5,1,6,2,7])
print(np.argsort(x))
print(x[x.argsort()])
print(x)

[2 4 0 1 3 5]
[1 2 3 5 6 7]
[3 5 1 6 2 7]


### You can use it to match up values from separate arrays

In [3]:
grade = np.array([3, 5, 1, 6, 2, 7])
ages = np.array([8, 10, 6, 11, 7, 12])

In [5]:
sort_index = np.argsort(ages)

In [6]:
print(grade[sort_index])
print(ages[sort_index])

[1 2 3 5 6 7]
[ 6  7  8 10 11 12]


### What if you want the comma seperators between values? 

In [7]:
print(list(grade[sort_index]))

[1, 2, 3, 5, 6, 7]


### Can also indirectly sort in descending order

In [9]:
print(list(ages[sort_index])[::-1])

[12, 11, 10, 8, 7, 6]
